-- MySQL Script generated by MySQL Workbench
-- Sun Dec 21 20:35:49 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user` (
  `user_id` INT NOT NULL,
  `user_type` VARCHAR(45) NULL COMMENT 'vendor\nbuyer\n',
  `user_login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `pay_password` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `qq` VARCHAR(45) NULL,
  `wechat` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_seller_shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_seller_shop` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_seller_shop` (
  `shop_id` INT NOT NULL,
  `platform_id` VARCHAR(45) NULL,
  `user_id` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `wangwang` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `postcode` VARCHAR(45) NULL,
  `comment` VARCHAR(2000) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`shop_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_platform` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_platform` (
  `platform_id` INT NOT NULL,
  `platform_name` VARCHAR(45) NULL,
  `platform_url` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`platform_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_recharge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_recharge` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_recharge` (
  `recharge_id` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `recharge_time` VARCHAR(45) NULL,
  `recharge_type` VARCHAR(45) NULL COMMENT '押金\n买点',
  PRIMARY KEY (`recharge_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_membership` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_membership` (
  `user_id` INT NOT NULL,
  `membership_type` VARCHAR(45) NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `create_time` DATETIME NULL DEFAULT today,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `cash` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_bank` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_bank` (
  `user_bank_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `bank_type` VARCHAR(45) NULL COMMENT '支付宝\n财付通\n银行',
  `account_name` VARCHAR(45) NULL,
  `account_number` VARCHAR(45) NULL,
  `branch` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `comment` VARCHAR(2000) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`user_bank_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_cashout`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_cashout` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_cashout` (
  `cashout_id` INT NOT NULL,
  `amount` VARCHAR(45) NULL,
  `points` VARCHAR(45) NULL,
  `fee` VARCHAR(45) NULL,
  `cashout_time` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL COMMENT 'request\napproved\ndenied\ndone\n',
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`cashout_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_points_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_points_transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_points_transaction` (
  `points_tran_id` INT NOT NULL,
  `amount` INT NULL,
  `type` VARCHAR(45) NULL,
  `tran_time` DATETIME NULL,
  PRIMARY KEY (`points_tran_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_balance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_balance` (
  `balance_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `points` DECIMAL(10,0) NULL,
  `cash` DECIMAL(10,0) NULL,
  `cash_frozen` DECIMAL(10,0) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`balance_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_activity` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_task` (
  `task_id` INT NOT NULL,
  `shop_id` INT NULL,
  `product_id` INT NULL COMMENT '数量\n',
  `commission` VARCHAR(45) NULL,
  `extra` DECIMAL(10,0) NULL,
  `total_tasks` INT NULL,
  `terminal` VARCHAR(45) NULL COMMENT '手机\nPC\n',
  `task_type` VARCHAR(45) NULL COMMENT '直通车\n聚划算\n',
  `pay_by` VARCHAR(45) NULL COMMENT '商家\n\n平台\n',
  `status` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_task_buyer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_task_buyer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_task_buyer` (
  `task_buyer_id` INT NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `task_id` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`task_buyer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_task_user_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_task_user_activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_task_user_activity` (
  `task_status_id` INT NOT NULL,
  `user_task_id` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  PRIMARY KEY (`task_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_featured_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_featured_task` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_featured_task` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_task_status_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_task_status_history` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_task_status_history` (
  `task_status_history_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `create_time` DATETIME NULL,
  `create_by` VARCHAR(45) NULL,
  PRIMARY KEY (`task_status_history_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_post` (
  `post_id` INT NOT NULL,
  `post_type` VARCHAR(45) NULL COMMENT '公告\n问题\n',
  `title` VARCHAR(45) NULL,
  `content` BLOB NULL,
  `status` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_shop_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_shop_product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_shop_product` (
  `product_id` INT NOT NULL,
  `shop_id` VARCHAR(45) NULL,
  `product_price` VARCHAR(45) NULL COMMENT '数量\n',
  `product_name` VARCHAR(45) NULL,
  `product_desc` VARCHAR(45) NULL,
  `product_image` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_buyer_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_buyer_account` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_buyer_account` (
  `user_account_id` INT NOT NULL,
  `user_id` INT NULL,
  `account_login` VARCHAR(45) NULL,
  `platform_id` VARCHAR(45) NULL,
  `address_id` INT NULL,
  `wangwang` VARCHAR(45) NULL,
  `ww_screenshot` VARCHAR(255) NULL,
  `status` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`user_account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user_address` (
  `address_id` INT NOT NULL,
  `user_id` INT NULL,
  `address_type` VARCHAR(45) NULL,
  `recipient` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `street_address` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_post_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_post_status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_post_status` (
  `post_status_id` INT NOT NULL,
  `post_id` VARCHAR(45) NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  `display_order` INT NULL COMMENT 'a number determines the display order',
  `created_time` DATETIME NULL,
  `created_by` VARCHAR(45) NULL,
  `lastupdated_time` DATETIME NULL,
  `lastupdated_by` VARCHAR(45) NULL,
  PRIMARY KEY (`post_status_id`))
ENGINE = InnoDB
COMMENT = 'this table determines whether a post is shown';

USE `mydb` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

USE `mydb`;
DROP  IF EXISTS `mydb`.`routine1`;

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
